version: '3.9'
services:
  php:
    build: ./provision/php_hostgator
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html

  db:
    image: percona:5.7-centos
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

volumes:
  db:
